---
- hosts: localhost
  tasks: 
    - name: Install Pip
      package:
        name: python-pip
        state: present
    - name: Install docker-py
      pip:
        name: docker-py
    - name: Build Docker Image
      docker_image:
        name: custom
        path: "/root/Docker"
        state: build
    - name: Running Container
      docker_container:
        name: my
        image: custom
        state: started
   

































