- name: Launch httpd
  hosts: localhost
  tasks: 
   - name: httpd Launch
     yum:
       name: httpd
       state: present
   - name: Httpd service
     service:
       name: httpd
       state: started
